name: Build

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - run: ./fetch-tdx-measure.sh
    - run: ./fetch-ovmf.sh
    - run: ./measure.sh

    - name: Hash platform measurements
      shell: bash
      id: hash
      run: |
        echo stdout=sha256:$(sudo sha256sum hardware-measurements.json | cut -d ' ' -f 1 | sudo tee tinfoil.hash) >> $GITHUB_OUTPUT

    - name: Attest
      uses: actions/attest@v1
      id: attest
      with:
        subject-name: hardware-measurements.json
        subject-digest: ${{ steps.hash.outputs.stdout }}
        predicate-type: https://tinfoil.sh/predicate/tdx-hardware-measurements/v1
        predicate-path: hardware-measurements.json

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          hardware-measurements.json
          tinfoil.hash
